name: Benchmark Report

permissions:
  contents: write

on:
  push:
    branches:
      - "*"
    paths-ignore:
      - 'README.md'
      - 'docs/**'
  workflow_dispatch:  # Allow manual triggering of the workflow

jobs:
  benchmark:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4.2.0

      # Cache for .NET packages
      - name: Cache .NET packages
        uses: actions/cache@v3
        with:
          path: |
            ~/.nuget/packages
            ~/.local/share/NuGet/Cache
          key: ${{ runner.os }}-nuget-${{ hashFiles('**/*.csproj') }}
          restore-keys: |
            ${{ runner.os }}-nuget-

      # Setup .NET environment
      - name: Setup .NET
        uses: actions/setup-dotnet@v4.0.1
        with:
          dotnet-version: '8.0.402'

      # Setup R environment
      - name: Setup R
        uses: r-lib/actions/setup-r@v2
      
      # Cache R packages
      - name: Cache R packages
        uses: actions/cache@v3
        with:
          path: ${{ env.R_LIBS_USER }}
          key: ${{ runner.os }}-r-${{ hashFiles('**/DESCRIPTION') }}
          restore-keys: |
            ${{ runner.os }}-r-

      # Install required R packages
      - name: Install R packages
        run: |
          Rscript -e 'install.packages(c("ggplot2", "gplots"), repos="https://cloud.r-project.org")'

      # Restore .NET dependencies
      - name: Restore .NET dependencies
        run: dotnet restore

      # Build the project
      - name: Build the project
        run: dotnet build -c Release --no-restore

      # Run Tests
      - name: Run Tests
        run: dotnet test --no-build --verbosity normal -c Release

      # Publish the project
      - name: Publish
        run: dotnet publish -c Release --verbosity normal -o ./publish/

      # Run Benchmarks
      - name: Run Benchmarks
        run: dotnet "./publish/BigFilesUtils.dll" -f "*"

      # Clean docs directory
      - name: Clean docs directory
        run: |
          rm -rf docs/*
          mkdir -p docs/

      # Move benchmark results
      - name: Move benchmark results
        run: |
          # Create docs directory if it doesn't exist
          mkdir -p docs/
          # Move markdown reports
          mv BenchmarkDotNet.Artifacts/results/*-report-github.md docs/ || echo "No GitHub markdown report found!"
          # Move barplot images
          mv BenchmarkDotNet.Artifacts/results/*-barplot.png docs/ || echo "No barplot found!"
          # Move additional plots
          mv BenchmarkDotNet.Artifacts/results/*-measurement.png docs/ || echo "No measurement plot found!"
          mv BenchmarkDotNet.Artifacts/results/*-distribution.png docs/ || echo "No distribution plot found!"
          # Move CSV and HTML reports
          mv BenchmarkDotNet.Artifacts/results/*.csv docs/ || echo "No CSV report found!"
          mv BenchmarkDotNet.Artifacts/results/*.html docs/ || echo "No HTML report found!"
      

        # Update README.md with benchmark results
      - name: Update README.md
        run: |
          # Remove existing benchmark results from README.md
          sed -i '/<!-- BENCHMARK RESULTS START -->/,/<!-- BENCHMARK RESULTS END -->/d' README.md
          # Add new benchmark results to README.md
          echo '<!-- BENCHMARK RESULTS START -->' >> README.md
          echo '' >> README.md
          echo '## Benchmark Results' >> README.md
          echo '' >> README.md
          echo '*Last updated on '"$(date -u)"' UTC*' >> README.md
          echo '' >> README.md
          # Include the content of the GitHub report markdown
          cat docs/*-report-github.md >> README.md
          echo '' >> README.md
          # Include the barplot image
          for img in docs/*-barplot.png; do
            echo "### Performance Barplot" >> README.md
            echo "![Benchmark Barplot]($img)" >> README.md
            echo '' >> README.md
          done
          # Include additional plots
          for img in docs/*-measurement.png; do
            echo "### Measurement Overhead Plot" >> README.md
            echo "![Measurement Overhead Plot]($img)" >> README.md
            echo '' >> README.md
          done
          for img in docs/*-distribution.png; do
            echo "### Distribution Plot" >> README.md
            echo "![Distribution Plot]($img)" >> README.md
            echo '' >> README.md
          done
          echo '<!-- BENCHMARK RESULTS END -->' >> README.md
      
      
        # Commit and push changes
      - name: Commit and push changes
        run: |
          git config --local user.name "github-actions[bot]"
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git add docs/*-report-github.md || echo "No markdown file to add!"
          git add docs/*-barplot.png || echo "No barplot image to add!"
          git add README.md
          git commit -m "Update benchmark results in README"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        continue-on-error: true
