name: Benchmark and Markdown Report

permissions:
  contents: write

on:
  push:
    branches:
      - "*"
  workflow_dispatch:  # Allow manual triggering of the workflow

jobs:
  benchmark:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4.2.0
      with:
        token: ${{ secrets.GITHUB_TOKEN }}

    - name: Setup .NET
      uses: actions/setup-dotnet@v4.0.1
      with:
        dotnet-version: '8.0.402'

    - name: Restore dependencies
      run: dotnet restore

    - name: Build the project
      run: dotnet build --no-restore -c Release
      
    - name: Publish
      run: dotnet publish -c Release --verbosity normal -o ./publish/
      
    - name: Archive
      uses: actions/upload-artifact@v4.4.0
      with:
        name: benchmarks_source
        path: ./publish/*
      
    - name: Run Benchmarks
      run: dotnet "./publish/BigFilesUtils.dll" -f "*"

    - name: Upload benchmark results
      uses: actions/upload-artifact@v4.4.0
      with:
        name: benchmark_results
        path: ./BenchmarkDotNet.Artifacts/results/*

    - name: Commit Markdown report to repository
      run: |
        mkdir -p docs/
        mv BenchmarkDotNet.Artifacts/results/*.md docs/ || echo "No markdown file found!"
        git config --local user.name "github-actions[bot]"
        git config --local user.email "github-actions[bot]@users.noreply.github.com"
        git add docs/*.md || echo "No markdown file to add!"
        git commit -m "Add benchmark markdown report"
        git push
      continue-on-error: true # Avoid failing the pipeline if the markdown file is missing
