name: Benchmark and Markdown Report

permissions:
  contents: write

on:
  push:
    branches:
      - "*"
  workflow_dispatch:  # Allow manual triggering of the workflow

jobs:
  benchmark:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4.2.0
      with:
        token: ${{ secrets.GITHUB_TOKEN }}

    - name: Setup .NET
      uses: actions/setup-dotnet@v4.0.1
      with:
        dotnet-version: '8.0.402'
        
    - name: Setup R
      uses: r-lib/actions/setup-r@v2
      
    - name: Install R packages
      run: |
        Rscript -e 'install.packages("ggplot2", repos="http://cran.rstudio.com")'

    - name: Restore dependencies
      run: dotnet restore

    - name: Build the project
      run: dotnet build --no-restore -c Release
      
    - name: Publish
      run: dotnet publish -c Release --verbosity normal -o ./publish/
      
    - name: Archive
      uses: actions/upload-artifact@v4.4.0
      with:
        name: benchmarks_source
        path: ./publish/*
      
    - name: Run Benchmarks
      run: dotnet "./publish/BigFilesUtils.dll" -f "*"
      
    - name: Run R script to generate plot
      run: |
        Rscript ./.scripts/generate_plot.R

    - name: Upload benchmark results
      uses: actions/upload-artifact@v4.4.0
      with:
        name: benchmark_results
        path: ./BenchmarkDotNet.Artifacts/results/*

    - name: Commit Markdown report to repository
      run: |
        mkdir -p docs/
        mv BenchmarkDotNet.Artifacts/results/*.md docs/ || echo "No markdown file found!"
        mv BenchmarkDotNet.Artifacts/results/*.png docs/ || echo "No plot file found!"
        git config --local user.name "github-actions[bot]"
        git config --local user.email "github-actions[bot]@users.noreply.github.com"
        git add docs/*.md || echo "No markdown file to add!"
        git add docs/*.png || echo "No plot file to add!"
        git commit -m "Add benchmark markdown report and plot"
        git push
      continue-on-error: true
